### ISSUE TITLE
[Quest] Spectre of the Black Rider - Black Rider Doesn't Despawn At Dawn

### ISSUE THREAD

**Issue by MasterTeal** [echoes-emu/echoes-bt#417]
Quest: Spectre of the Black Rider (Shire)
Black Rider should only be there at night, but is also present during daytime.

Quest Giver Loc: bx101 by116 c0 ox103.122 oy112.98 oz364.334 r39 (Instance 0)
Quest Objective Loc: bx101 by116 c0 ox21.8773 oy38.9207 oz340.404 r173 (Instance 0)

**Comment by dawnz85** [comment]
Fixed

**Comment by dawnz85** [comment]
Generator is now night only but doesn't despawn this NPC at dawn

**Comment by echoes-emu** [comment]
The spawn/despawn hour is probably just offset from what it should be. Deferring this as cosmetic

**Comment by bcp19** [comment]
Tested this on a server reboot during the 'night' phase, NPC still appears.

**Comment by bcp19** [comment]
This issue has been resolved as the NPC does now vanish during the day and reappears at night.
